'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://127.0.0.1:8030';
type Obs = {id:string;source_type:string;title?:string;source_url?:string;context_es?:string;segments:any[]};

export default function Home(){
 const [tab,setTab]=useState<'capture'|'youtube'|'corpus'>('capture'); const [items,setItems]=useState<Obs[]>([]); const [msg,setMsg]=useState('');
 const media=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]); const [blob,setBlob]=useState<Blob|null>(null); const [recording,setRecording]=useState(false);
 async function refresh(){try{const r=await fetch(`${API}/api/v1/observations`); if(r.ok)setItems(await r.json())}catch{}}
 useEffect(()=>{refresh()},[]);
 async function toggleRecord(){ if(recording){media.current?.stop();setRecording(false);return;} const stream=await navigator.mediaDevices.getUserMedia({audio:true}); const rec=new MediaRecorder(stream);chunks.current=[];rec.ondataavailable=e=>chunks.current.push(e.data);rec.onstop=()=>{setBlob(new Blob(chunks.current,{type:rec.mimeType}));stream.getTracks().forEach(t=>t.stop())};media.current=rec;rec.start();setRecording(true); }
 async function capture(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!blob)return setMsg('Primero graba audio.');const fd=new FormData(e.currentTarget);fd.append('audio',blob,'capture.webm');setMsg('Guardando captura...');const r=await fetch(`${API}/api/v1/observations/capture`,{method:'POST',body:fd});setMsg(r.ok?'Captura incorporada al corpus.':'No se pudo guardar.');if(r.ok){setBlob(null);e.currentTarget.reset();refresh()}}
 async function youtube(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setMsg('Creando observación...');const r=await fetch(`${API}/api/v1/observations/youtube`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:fd.get('url'),context_es:fd.get('context_es'),language_variant:fd.get('language_variant')})}); if(!r.ok)return setMsg('No se pudo crear la observación.');const o=await r.json();const start=Number(fd.get('start'));const end=Number(fd.get('end'));const sr=await fetch(`${API}/api/v1/observations/${o.id}/segments`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({start_seconds:start,end_seconds:end,transcription_human:fd.get('transcription_human')||null,phonetic_human:fd.get('phonetic_human')||null,translation_es:fd.get('translation_es')||null,context_es:fd.get('segment_context')||null})});setMsg(sr.ok?'Segmento de YouTube guardado en el corpus.':'Observación creada, pero falló la extracción del segmento.');refresh();}
 return <main><header><div><b>MAYA</b><span>Speech Lab</span></div><p>Corpus multimodal colaborativo · evidencia primero, modelos después</p></header>
 <nav>{[['capture','＋ Captura Express'],['youtube','▶ YouTube Annotator'],['corpus','⌕ Corpus Explorer']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as any)}>{l}</button>)}</nav>
 {msg&&<div className="notice">{msg}</div>}
 {tab==='capture'&&<section><h1>CapturaAudioyTextoExpress</h1><p>Graba unos segundos. Después describe qué ocurrió. La evidencia original queda preservada.</p><form onSubmit={capture}><button type="button" className={recording?'recording record':'record'} onClick={toggleRecord}>{recording?'■ Terminar':'● Grabar audio'}</button>{blob&&<p className="ready">✓ Audio listo para guardar</p>}<label>¿Qué está pasando?<textarea name="context_es" placeholder="Describe en español lo que viste o el contexto..."/></label><div className="grid"><label>¿Qué crees que se dijo?<textarea name="transcription_human"/></label><label>¿Qué significa en español?<textarea name="translation_es"/></label></div><div className="grid"><label>Variante<input name="language_variant" placeholder="p. ej. Maya Yucateco"/></label><label>Lugar<input name="location" placeholder="p. ej. Valladolid, Yucatán"/></label></div><button className="primary">Guardar en el corpus</button></form></section>}
 {tab==='youtube'&&<section><h1>YouTube Annotator</h1><p>Pega un video y selecciona exactamente la ventana que deseas incorporar y etiquetar.</p><form onSubmit={youtube}><label>URL de YouTube<input required name="url" type="url" placeholder="https://youtu.be/..."/></label><div className="grid"><label>Inicio (segundos)<input required name="start" type="number" step="0.001" min="0" defaultValue="0"/></label><label>Fin (segundos)<input required name="end" type="number" step="0.001" min="0.001" defaultValue="10"/></label></div><label>Contexto general<textarea name="context_es" placeholder="¿De qué trata este material?"/></label><label>Variante<input name="language_variant" placeholder="Si se conoce"/></label><div className="grid"><label>Transcripción humana<textarea name="transcription_human"/></label><label>Fonética / IPA<textarea name="phonetic_human"/></label></div><label>Traducción al español<textarea name="translation_es"/></label><label>¿Qué ocurre en este segmento?<textarea name="segment_context"/></label><button className="primary">Extraer y guardar segmento</button></form></section>}
 {tab==='corpus'&&<section><h1>Corpus Explorer</h1><div className="stats"><b>{items.length}</b> observaciones · <b>{items.reduce((a,o)=>a+(o.segments?.length||0),0)}</b> segmentos</div>{items.map(o=><article key={o.id}><div className="pill">{o.source_type}</div><h3>{o.title||o.id}</h3><p>{o.context_es||'Sin descripción contextual.'}</p>{o.segments?.map(s=><div className="segment" key={s.id}><b>{s.start_seconds.toFixed(2)}–{s.end_seconds.toFixed(2)} s</b>{s.audio_url&&<audio controls src={s.audio_url}/>}<small>{s.transcription_human||s.translation_es||'Pendiente de anotación'}</small></div>)}</article>)}</section>}
 <footer>Prof. Alberto Muñoz · Maya Multimodal Corpus & Speech Research Platform</footer></main>
}
